import { FG_ENVIRONMENT } from './fg-environment.token';
import {
  FG_ROUTING_LOGOUT_PATH,
  FG_ROUTING_HOME_PATH,
  FG_ROUTING_LOGIN_PATH,
  FG_ROUTING_PASSWORD_CHANGE_PATH,
} from './fg-routing.token';
import { ACTIVE_ELEMENT } from './fg-active-element.token';

export {
  ACTIVE_ELEMENT,
  FG_ENVIRONMENT,
  FG_ROUTING_HOME_PATH,
  FG_ROUTING_LOGIN_PATH,
  FG_ROUTING_LOGOUT_PATH,
  FG_ROUTING_PASSWORD_CHANGE_PATH,
};
