import { ModuleFederationConfig } from '@nx/module-federation';

const config: ModuleFederationConfig = {
  name: 'react-host',
  /**
   * To use a remote that does not exist in your current Nx Workspace
   * You can use the tuple-syntax to define your remote
   *
   * remotes: [['my-external-remote', 'https://nx-angular-remote.netlify.app']]
   *
   * You _may_ need to add a `remotes.d.ts` file to your `src/` folder declaring the external remote for tsc, with the
   * following content:
   *
   * declare module 'my-external-remote';
   *
   */
  remotes: [
    'react_view_login',
    'react_view_home',
    'react_view_calc',
  ],
  
  additionalShared: [ 
    ['@angular/core', { 
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['@angular/core/primitives/signals', { 
        eager: true, 
        strictVersion: true,
        singleton: true,
        requiredVersion: 'auto',
    }],
    ['@angular/core/primitives/event-dispatch', { 
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['rxjs', {
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['rxjs/operators', {
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['@angular/material', {
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['@angular/cdk', {
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
    ['zod', {
      eager: true, 
      strictVersion: true,
      singleton: true,
      requiredVersion: 'auto',
    }],
  //   [ '@angular/cdk/schematics', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/a11y', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/accordion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/bidi', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/clipboard', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/collections', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/dialog', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/drag-drop', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/keycodes', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/layout', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/listbox', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/menu', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/overlay', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/platform', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/portal', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/scrolling', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/stepper', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/table', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing/selenium-webdriver', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing/testbed', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/text-field', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/tree', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/a11y', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/accordion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/bidi', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/clipboard', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/collections', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/dialog', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/drag-drop', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/keycodes', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/layout', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/listbox', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/menu', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/overlay', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/platform', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/portal', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/scrolling', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/stepper', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/table', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/text-field', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/tree', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/schematics', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/a11y', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/accordion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/bidi', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/clipboard', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/collections', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/dialog', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/drag-drop', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/keycodes', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/layout', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/listbox', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/menu', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/overlay', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/platform', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/portal', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/scrolling', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/stepper', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/table', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing/selenium-webdriver', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing/testbed', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/text-field', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/tree', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/a11y', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/accordion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/bidi', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/clipboard', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/coercion', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/collections', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/dialog', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/drag-drop', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/keycodes', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/layout', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/listbox', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/menu', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/observers', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/overlay', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/platform', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/portal', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/private', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/scrolling', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/stepper', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/table', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/testing', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/text-field', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  //   }],
  //   [ '@angular/cdk/tree', {
  //     eager: true, 
  //     strictVersion: true,
  //     singleton: true,
  //     requiredVersion: 'auto',
  
  ],
};

/**
 * Nx requires a default export of the config to allow correct resolution of the module federation graph.
 **/
export default config;
